from pydantic import BaseModel, Field
from typing import List
import uuid


class MinimalSource(BaseModel):
    """. Pydantic schema representing exact coordinate positions inside
    files.

    Attributes:
        file_path (str): Relative or absolute filesystem path to the target.
        first_character_index (int): Starting position boundary offset.
        last_character_index (int): Ending position boundary offset.
    """
    file_path: str
    first_character_index: int
    last_character_index: int


class UnansweredQuestion(BaseModel):
    """. Pydantic validation structural layout for an incoming text query.

    Attributes:
        question_id (str): Unique tracking sequence generated via UUID4.
        question (str): Text parameter query submitted by evaluation engines.
    """
    question_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    question: str


class AnsweredQuestion(UnansweredQuestion):
    """. Schema tracking evaluation data matching ground truth references.

    Attributes:
        sources (List[MinimalSource]): Perfect target location mapping blocks.
        answer (str): Validated context response string from experts.
    """
    sources: List[MinimalSource]
    answer: str


class RagDataset(BaseModel):
    """. Schema matching root json array structures inside dataset files.

    Attributes:
        rag_questions (List[AnsweredQuestion | UnansweredQuestion]): Mix of
            evaluation questions containing answer objects or empty queries.
    """
    rag_questions: List[AnsweredQuestion | UnansweredQuestion]


class MinimalSearchResults(BaseModel):
    """. Standard footprint capturing data generated by search routines.

    Attributes:
        question_id (str): Reference string tracing back to original prompts.
        question (str): The natural language query mapped for validation.
        retrieved_sources (List[MinimalSource]): Collection tracking the top-k
            fetched locations.
    """
    question_id: str
    question: str
    retrieved_sources: List[MinimalSource]


class MinimalAnswer(MinimalSearchResults):
    """. Structure containing validation metadata and generated texts.

    Attributes:
        answer (str): The concise string result compiled by local models.
    """
    answer: str


class StudentSearchResults(BaseModel):
    """. Structure holding batch search summaries for file pipeline tracking.

    Attributes:
        search_results (List[MinimalSearchResults]): Core listing recording
            every search output.
        k (int): Parameter restriction bounding the fetched candidates list.
    """
    search_results: List[MinimalSearchResults]
    k: int


class StudentSearchResultsAndAnswer(StudentSearchResults):
    """. Complete final file output structure containing searches and answers.

    Attributes:
        search_results (List[MinimalAnswer]): Complete structural items
            capturing search references along with model inference outputs.
    """
    search_results: List[MinimalAnswer]  # type: ignore[assignment]
